In [23]:
import datetime
import yfinance as yf
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource

# Descarga los datos
start = datetime.datetime(2024, 10, 1)
end = datetime.datetime(2024, 10, 25)
df = yf.download("TEF", start=start, end=end)
df

[*********************100%***********************]  1 of 1 completed

                           Adj Close  Close  High   Low  Open   Volume
Date
2024-10-01 00:00:00+00:00       4.83   4.83  4.85  4.81  4.85   400700
2024-10-02 00:00:00+00:00       4.76   4.76  4.79  4.75  4.78   420200
2024-10-03 00:00:00+00:00       4.73   4.73  4.76  4.68  4.69  1071200
2024-10-04 00:00:00+00:00       4.75   4.75  4.76  4.71  4.71   369200
2024-10-07 00:00:00+00:00       4.78   4.78  4.79  4.75  4.77   348500
2024-10-08 00:00:00+00:00       4.80   4.80  4.82  4.78  4.80   638400
2024-10-09 00:00:00+00:00       4.81   4.81  4.82  4.80  4.80   245500
2024-10-10 00:00:00+00:00       4.77   4.77  4.82  4.77  4.82   216100
2024-10-11 00:00:00+00:00       4.77   4.77  4.80  4.76  4.76   252100
2024-10-14 00:00:00+00:00       4.78   4.78  4.79  4.76  4.78   223800
2024-10-15 00:00:00+00:00       4.76   4.76  4.81  4.75  4.76   346600
2024-10-16 00:00:00+00:00       4.88   4.88  4.90  4.84  4.84   363400
2024-10-17 00:00:00+00:00       4.83   4.83  4.87  4.82  4.87   501100
2024-10-18 00:00:00+00:00       4.77   4.77  4.79  4.75  4.75   335900
2024-10-21 00:00:00+00:00       4.72   4.72  4.77  4.71  4.76   314300
2024-10-22 00:00:00+00:00       4.67   4.67  4.70  4.66  4.67   295900
2024-10-23 00:00:00+00:00       4.64   4.64  4.66  4.63  4.64   348500
2024-10-24 00:00:00+00:00       4.66   4.66  4.71  4.65  4.67   313000

In [25]:

# configuraciÃ³n del grafico
p = figure(x_axis_type="datetime", width=1000, height=300)
p.title.text = "Candlestick Chart"



hours_12 = 12 * 60 * 60 * 1000  # en milisegundos

# aqui filtramos los datos de subida y bajada
inc = df['Close'] > df['Open']
dec = df['Close'] < df['Open']

# datos para dias de subida en verde
source_inc = ColumnDataSource(data=dict(
    x=df.index[inc],
    y=(df['Open'][inc] + df['Close'][inc]) / 2,
    height=abs(df['Open'][inc] - df['Close'][inc])
))

# datos para dias de bajada en rojo
source_dec = ColumnDataSource(data=dict(
    x=df.index[dec],
    y=(df['Open'][dec] + df['Close'][dec]) / 2,
    height=abs(df['Open'][dec] - df['Close'][dec])
))

# dibuja los rectangulos  subida en verde y bajada rojo
p.rect(x='x', y='y', width=hours_12, height='height', source=source_inc, fill_color="green", line_color="green")
p.rect(x='x', y='y', width=hours_12, height='height', source=source_dec, fill_color="red", line_color="red")

output_file("telefonica.html")
show(p)